[package]
name          = "safe_nfs"
version       = "0.1.0"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
description   = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.net/safe_nfs/latest"
repository    = "https://github.com/maidsafe/safe_nfs"
readme        = "README.md"
license       = "GPL-3.0"
homepage      = "http://maidsafe.net"

[dependencies]
# ---- Maidsafe ----
routing         = "0.3.*"
safe_client     = "0.1.*"
self_encryption = "0.2.*"

# ---- Others ----
time            = "*"
sodiumoxide     = "*"
rustc-serialize = "*"

[features]
use-mock-routing = ["safe_client/use-mock-routing"]
